name: Auto Close New PRs

on:
  pull_request:
    types:
      - opened

permissions:
  pull-requests: write 
  
jobs:
  auto_close:
    runs-on: ubuntu-latest

    steps:
      - name: Close newly opened PRs
        uses: peter-evans/close-pull@v3
        with:
          message: "This PR has been closed automatically."
